language: java
jdk: openjdk8
deploy:
  provider: releases
  api_key:
    secure: G1/40NF0zGRvPSVzpL3Bwg/ztc5Xwz3S4Lyw6VH4WGsGL0QLKodRlMXlyL9NQevn0dAnyWEiGk6nlHzQ4QedAQlJRTwwk10H3fLNDWBU84FCFqFqaE2dc4P15XimBG/jNkaBcfOnmo5d0ZLSPYjXok5DXzQArou2mi9/h0uqoHqc9CI2QTP9knoHfDtYa04fvKTI18w/koF2VMFdZj3S0B/2o02HAQUwbsXpbrzSO2UgPRJCnE+Gw+H5EULZX8f+Y2QYlAdxxtHwbwXC/xjnGLjNMfIT4aX3R1T6d4YsRwdjUXlwqgHSPPOGgaVl+dXEt4XBF2ybvjgHbhK0BkK4xvz00d5GRX8GofEjiKIoFBeSFuF+SuA1Ozqe1yVRyxlFkrQPkVeAGuzaHpD96jClA19AdEwiX8HALJmfL6V9gr+JYd93EVMTp7j2piMD9BP+NVfoO0XB3/ucYRaMnedcFlONx6QCy7f6f/coUrRgTE4txHRh2cwkI32OYeZcyBoMDrknKor4Kr12HkQCMu8TN6a6M5hRcExZnMxfZmpc2v68l5sU+dvLZiJ4/fHFwmRbZ0NiODhX6jhNoJxkvkZ9alN3zNjgUv1fy71lgjkHUBc6fAFacK/1O2ScDOiBxrv8rEVpVPoZZ7Ih/qxvX6g14zF739+/PZLcSoMnMKsCgF4=
  file_glob: true
  file: build/libs/*
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xlr-xld-insights-plugin
notifications:
  slack:
    secure: oVFDhxiJ9qM6us51+kWk3Cj7jUWJSuu/eBm4Y6BnttL/NgaSn/rSpmAprtxwCoBF8r1Dib1okHdVVnjILFqotkvnSHgp8Ul4fhrfnthEdtXU1hTN3J53YGa+vlBkLBc8EagetgJ4WL97qAWSvfwhdpaUSD9+/Ha63T4lbjrWcfGcYx35px+tJQgT3D643apH3hbRnHjlEoNBn7POYw8HJvlRc9NzUdIHkS8F4z4MksckZ0xc/sDZrlB4bXRIAD9Sb5tPf1qV6uF9OtW5YD5j6B4DaN35FxSX+gXDTbaFWkySqsj28owmi18qSi1k8Pl6zLv+Xitj8Un94JFNIozvIgGVwGOuD/k0pgVPRQSqTuIQ1JNw17fYwOASpZvRiZHh4ua7i+UIJxVMelc3d/dUT4hy6izadzeFmw60MWNJSwGmxkbr4aoW4u3nnB27SJ0d7O8uTONiramXYitaBfqhj9A+30EKkcMCu0D8g6e9i4O9ttmroA0sntO24zaaYMFzkRTEZC6Kmdu8bDRGsktRyTeuClKI5Ux+fe9GQalkSeNBPARjtANZDVHvjf2RPdwV19G39t04reuPINEPr4BVBCWBb/qV7HQMdR2K/VQkr+uzNnSg/5ry0dceMUdkzvpR1Rn+1F2U6s3c5F85j4pExRDoJu3rsuHBs4S43TBVKHs=
